package data.exceptions

class TaskStateNameException() : Exception("Task Name Already exist!")